mongodb_install_tar="mongodb-linux-x86_64-2.6.7.tgz"
mongodb_shard_install="shard_install.sh"
hosts_file="hosts"
mongodb_dir=`echo $mongodb_install_tar|cut -d "." -f1,2,3`
mongodb_root_path=/export
mongodb_path=$mongodb_root_path/servers/mongodb/bin
mongodb_server_path=$mongodb_root_path/servers/mongodb
mongodb_data_path=$mongodb_root_path/data/mongodb
key_file="key"
password="123456"
mongo_admin_user="admin"
mongo_admin_passwd="123456"
mongo_monitor_user="monitor"
mongo_monitor_passwd="123456"
mongod_port=20011
arbiter_port=20012
mongos_port=30017
config_port=30011
